### PR TITLE
Bump versioneer for python 3.12 compatibility

### LINKED ISSUE #50: Versioneer 0.18 incompatible with Python 3.12
Versioneer 0.18 uses `configparser.SafeConfigParser()`, which was removed in Python 3.12 (https://github.com/python/cpython/pull/92503)

I have tentatively upgraded the vendored file to versioneer==0.19, which allows me to install on 3.12 without issue, however this does also appear to break support for Python 2, so it may not be an ideal solution for you.

```python-traceback
> pip install --no-cache --force-reinstall pprofile

Collecting pprofile
  Downloading pprofile-2.1.0.tar.gz (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 kB 596.3 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      C:\Users\Daniel\AppData\Local\Temp\pip-install-5iyuhadx\pprofile_13a59f164ac44042a04c5f8208ddd6d4\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Daniel\AppData\Local\Temp\pip-install-5iyuhadx\pprofile_13a59f164ac44042a04c5f8208ddd6d4\setup.py", line 25, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Daniel\AppData\Local\Temp\pip-install-5iyuhadx\pprofile_13a59f164ac44042a04c5f8208ddd6d4\versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\Daniel\AppData\Local\Temp\pip-install-5iyuhadx\pprofile_13a59f164ac44042a04c5f8208ddd6d4\versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Daniel\AppData\Local\Temp\pip-install-5iyuhadx\pprofile_13a59f164ac44042a04c5f8208ddd6d4\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### PR DESCRIPTION
**Pull request by DanGonite57**
Fixes https://github.com/vpelletier/pprofile/issues/50

### CODE REVIEW

**Comment by dvzrv** [comment]
@vpelletier can this please be merged and released?
We are currently hitting this issue while rebuilding the distro against python 3.12 on Arch Linux

**Comment by vpelletier** [comment]
Thank you for the heads-up.

On a higher level, I am getting really annoyed with versioneer: I still like it as a feature, but I believe this is the 3rd time since I use it, and the second time in the two latest minor cpython versions, that versioneer is what is breaking compatibility, requiring the update of every repository where I use it.

Then there is also the perspective from the xz debacle, which, to me, also highlights how bundling files coming from 3rd-party projects (autogen in the case of xz) can be used to rope in obfuscated backdoors (and otherwise hostile code), which makes me even less happy with versioneer dropping anything but absolutely trivial files in the repository.

Overall, I think I would rather get rid of it (or otherwise push it outside of the repository) rather than keep chasing its latest version.

And on top of all this, I currently have very little spare time (and will not have for a few more months at least), which is not helping me in figuring out what other way I am more comfortable with. Pointers are welcome.

In the meantime, for distribution packaging purposes, are you able/is it a good idea to have you apply the present patch during packaging ?

**Comment by ekiefl** [comment]
I'm sad that I have to let pprofile loose from my package because of this. Thank you sincerely for the otherwise amazing project, I've used it happily for years.

**Comment by vpelletier** [comment]
Spare time is slowly becoming a thing again, so I'm finally back on this topic.

Is there a reason the version bump is only to 0.19, as opposed to jumping directly to now-current 0.29 ?

**Comment by DanGonite57** [comment]
I wanted to try to let you keep compatibility with as many versions of python 3 as possible, so I just went with the earliest compatible version. Otherwise, I don't remember encountering any particular issues when testing with versioneer 0.29 either.

(https://github.com/DanGonite57/pprofile/commits/test312/)

**Comment by vpelletier** [comment]
Mmh, looks like github failed to recognise that I rebased & merged this change from the command line. So I am closing this, but the change is now in master - and now to be released as 2.2.0 .

Sorry for the time it took for me to act on this.

**Comment by ekiefl** [comment]
Thanks!

**Pull request closed without merging**
